# Generated by Django 5.2.11 on 2026-05-01 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone / WhatsApp')),
                ('project_details', models.TextField(verbose_name='Project Details')),
                ('expected_budget', models.CharField(blank=True, max_length=100, verbose_name='Expected Budget')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Required Delivery Date')),
                ('is_aware_min_budget', models.BooleanField(default=False, verbose_name='أنا على وعي أن المشروع لن يكلف أقل من 5000 جنيه مصري')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('opened', 'Opened'), ('refused', 'Refused'), ('accepted', 'Accepted'), ('contacted', 'Contacted')], default='unread', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Message / Order',
                'verbose_name_plural': 'Messages & Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DevGrade', max_length=100, verbose_name='Site Name')),
                ('tagline', models.CharField(default='مشاريع Django جاهزة لطلاب الجامعات', max_length=200, verbose_name='Tagline')),
                ('meta_description', models.TextField(default='اشتري مشاريع Django احترافية جاهزة للمشاريع الجامعية. تحميل فوري أو تنفيذ مخصص حسب طلبك.', verbose_name='Default Meta Description')),
                ('meta_keywords', models.CharField(default='مشاريع django, مشاريع جامعية, علوم الحاسب, IT', max_length=300, verbose_name='Meta Keywords')),
                ('contact_email', models.EmailField(default='Medoledowork144@gmail.com', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, default='01272776895', max_length=50, verbose_name='Phone / WhatsApp')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics or any tracking code', verbose_name='Analytics Code')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stacks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('full_description', models.TextField(verbose_name='Full Description')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/', verbose_name='Thumbnail')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('gumroad_standard_url', models.URLField(blank=True, help_text='Gumroad purchase link for standard version', verbose_name='Gumroad URL')),
                ('standard_price', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='Standard Price (EGP)')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custom Price (EGP)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured?')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category', verbose_name='Category')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='projects.techstack', verbose_name='Tech Stack')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, verbose_name='Feature')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
    ]
