# Generated by Django 5.2.11 on 2026-04-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة / طلب', 'verbose_name_plural': 'الرسائل والطلبات'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='projectfeature',
            options={'ordering': ['order'], 'verbose_name': 'ميزة', 'verbose_name_plural': 'المميزات'},
        ),
        migrations.AlterModelOptions(
            name='projectscreenshot',
            options={'ordering': ['order'], 'verbose_name': 'لقطة شاشة', 'verbose_name_plural': 'لقطات الشاشة'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['name'], 'verbose_name': 'تقنية', 'verbose_name_plural': 'التقنيات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='message',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='ملاحظات شخصية مش هتظهر للعميل', verbose_name='ملاحظات الأدمن'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المطلوب'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expected_budget',
            field=models.CharField(blank=True, help_text='مثلاً: 2000-3000 جنيه', max_length=100, verbose_name='الميزانية المتوقعة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='inquiry_type',
            field=models.CharField(choices=[('custom_order', 'طلب مخصص'), ('general_inquiry', 'استفسار عام')], default='custom_order', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم التليفون / واتساب'),
        ),
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='projects.project', verbose_name='المشروع (اختياري)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='project_details',
            field=models.TextField(help_text='اشرحلي بالتفصيل اللي عايزه', verbose_name='تفاصيل المشروع'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='سعر التنفيذ المخصص (جنيه)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='رابط الديمو'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True, verbose_name='رابط التوثيق'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(verbose_name='وصف كامل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gumroad_standard_url',
            field=models.URLField(blank=True, help_text='رابط شراء النسخة العادية على Gumroad', verbose_name='رابط Gumroad'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منشور؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='وصف الميتا'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='page_title',
            field=models.CharField(blank=True, help_text='يتم استبدال عنوان الصفحة', max_length=200, verbose_name='عنوان الصفحة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='project',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=8, verbose_name='سعر النسخة العادية (جنيه)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.techstack', verbose_name='التقنيات المستخدمة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/thumbnails/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='feature',
            field=models.CharField(max_length=200, verbose_name='الميزة'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='projectfeature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image',
            field=models.ImageField(upload_to='projects/screenshots/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.project', verbose_name='المشروع'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='analytics_code',
            field=models.TextField(blank=True, help_text='كود Google Analytics أو أي tracking', verbose_name='كود التحليلات'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(default='Medoledowork144@gmail.com', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم التليفون / واتساب'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='نص الفوتر'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(default='اشتري مشاريع Django احترافية جاهزة لمشروع التخرج. تحميل فوري أو تنفيذ مخصص حسب طلبك.', verbose_name='وصف الميتا الافتراضي'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_keywords',
            field=models.CharField(default='مشاريع django, مشاريع تخرج, مشاريع جامعية, علوم الحاسب, IT', max_length=300, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='DevGrade', max_length=100, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(default='مشاريع Django جاهزة لطلاب الجامعات', max_length=200, verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(max_length=50, verbose_name='التقنية'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='الرابط'),
        ),
    ]
