# Generated by Django 5.2.13 on 2026-04-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_category_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, default='01272776895', max_length=50, verbose_name='رقم التليفون / واتساب'),
        ),
    ]
